### ISSUE TITLE
[chore] QA 수정사항 반영

### ISSUE THREAD

**Issue by jihyunniiii** [TelePigeon/TelePigeon-Android#39]
## What is this issue? 🛠
QA 수정사항을 반영합니다.

## Progress 🏃‍♀️
- [x] 방 삭제 페이지 -> 취소/확인 버튼 위치 바꾸기
- [x] 방 생성 페이지 -> 이름 엔터 불가 가능?
- [x] 상대 답변 확인하기 -> 확인하기 버튼이 disable 상태
- [x] 월간보고서 간격 맞추기
- [x] 캘린더 동그라미 색깔 바꾸기
- [x] 걱정 삭제 -> 취소/확인 버튼 위치 바꾸기
- [x] 걱정 설정 -> 완료하기 버튼 누르면 방 설정으로 이동
- [x] 키워드 설정 -> 추가 정보에서 연령대랑 관계 사이 공백 지우기 => 전체 간격 알맞게
- [x] 전체 키워드 설정 -> 최대 3개까지 선택할 수 있어요 삭제
- [x] 방 설정 -> 바텀시트 수정 -> 완료하기 안 눌림
- [x] 방 목록 조회에서 상대방이 방에서 나갔을 경우 분기처리 추가(sentence = 4 일 때 상대방이 방을 나갔어요 띄워주기)
- [x] 답변 전송 시 상대방이 방에서 나갔을 때 200OK conflict 에러 추가(노션에 반영되있음)

**Comment by tkdwns414** [comment]
방 리스트에서 새로고침 가능할까요?
